(function(_ds){var window=this;var JN=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},KN=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')},LN=function(a){a=a.wq;a=_ds.hG(new _ds.dG("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.R(_ds.cq(1,_ds.WF[void 0]||1)),XXX_2:_ds.R(_ds.cq(a,_ds.WF[void 0]||1))});return(0,_ds.Q)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var MN="onpointerover"in window?"pointerover":"mouseover",NN=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.D(a,"visually-hidden","",c))},VN=function(a){a.eventHandler.listen(a,"click",b=>void ON(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&ON(a,b)});a.eventHandler.listen(a,[MN,"focusin"],b=>void PN(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.h&&(QN(a,"_book")?a.removeAttribute("top-level-nav"):_ds.D(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.H.g());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.H.g()});a.eventHandler.listen(a,"scroll",()=>{_ds.D(a,"user-scrolled","")});a.eventHandler.listen(a.tb,"click",()=>{RN(a)});a.g&&(a.eventHandler.listen(a.g,"keyup",()=>void a.M.g()),a.eventHandler.listen(a.g,"focus",()=>void SN(a,"focus")));a.D&&a.eventHandler.listen(a.D,["click",
"keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.g&&(a.g.value="",a.g.focus());let c;null==(c=a.D)||c.classList.add("hidden");TN(a);UN(a);SN(a,b.type)}})},XN=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.F().hash&&c)WN(a,a.C);else{c=new _ds.vG;for(const d of a.C)_ds.uG(c,d)}},YN=async function(a){const b=await _ds.x();for(const c of a.C)b.unregisterIntersectionForElement(c)},ON=function(a,b){if(!b.defaultPrevented){var c=b.target;
"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.D(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&QN(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.D(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.h&&(d=a.h.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},PN=function(a,b){b.defaultPrevented||(b=_ds.oi(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.ad(b,_ds.$c(_ds.kj(b.href).href)))},RN=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.Ik(a.eventHandler,a,_ds.qf,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.o.removeAttribute("animatable")});_ds.D(a,"animatable","");b=_ds.Jc(a.m`animatable`);b(a.background,"animatable","");b(a.o,"animatable","");a.hasAttribute("collapsed")?(_ds.D(a,"aria-expanded","true",a.tb),_ds.D(a,"aria-label","Hide side navigation",a.tb),_ds.D(a,"data-title","Hide side navigation",a.tb),a.removeAttribute("collapsed"),ZN(a,
"Expanded book nav")):(a.tb.removeAttribute("aria-expanded"),_ds.D(a,"aria-label","Show side navigation",a.tb),_ds.D(a,"data-title","Show side navigation",a.tb),_ds.D(a,"collapsed",""),ZN(a,"Collapsed book nav"));await _ds.rj();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},SN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===
b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},$N=function(a){a.F=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},bO=function(a){const b=_ds.F().searchParams.get("nf");a.g&&b&&(a.g.value=b,aO(a))},aO=function(a){if(a.F.length){TN(a);UN(a);var b,c,d=null==(b=a.g)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.D)||e.classList.remove("hidden");
for(const g of a.F){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");
let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.Hc(f,_ds.Pg.g(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.M(LN,{wq:a}),b.appendChild(a))}}else null==(f=a.D)||f.classList.add("hidden")}},TN=function(a){for(const b of a.F){let c;b.classList.toggle("hidden",!(null==(c=a.g)||!c.value))}},UN=function(a){if(a.querySelector("mark")){var b=
[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.Hc(a,_ds.Pg.g(b))}}},WN=async function(a,b){if(a.v){var c=await _ds.x(),d=new _ds.vG,e=f=>{f=f.target;_ds.uG(d,f);a.C.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},QN=
function(a,b){let c=!1;if(a.h)for(const d of a.h.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.D(a,"hidden","",d);return c},cO=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.xj(_ds.F().pathname);a=`[href="${_ds.kj(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},dO=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},fO=async function(a){a.v&&(a.removeAttribute("user-scrolled"),await _ds.rj(),await eO(a),await a.T,await _ds.x(),await _ds.rj(),await eO(a))},
eO=async function(a){if(a.v&&a.h){await _ds.x();var b=a.h.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await gO(a,b))}},gO=async function(a,b){if(a.v){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Yk(b,a,!0).y;await _ds.rj();c&&_ds.D(a,"user-scrolled","")}},ZN=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},hO=class extends _ds.E{constructor(){super();
this.v=!1;this.D=this.g=this.G=this.h=null;this.F=[];this.eventHandler=new _ds.G;this.K=()=>{};this.C=new Set;this.J=this.V=!1;this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.tb=_ds.M(JN);this.o=_ds.M(KN);this.T=new Promise(a=>{this.K=a});this.H=new _ds.Ek(()=>{this.v&&NN(this)},20);this.M=new _ds.Ek(()=>{aO(this)},20)}static get observedAttributes(){return["collapsed","fixed","hidden"]}async connectedCallback(){this.v=!0;_ds.Xg(this,this.m`animatable`,
this.m`aria-expanded`,this.m`aria-label`,this.m`collapsed`,this.m`data-title`,this.m`fixed`,this.m`has-book-nav`,this.m`hidden`,this.m`top-level-nav`,this.m`user-scrolled`,this.m`visually-hidden`);_ds.Xh(this.background,this);this.hasAttribute("hidden")&&(_ds.D(this,"hidden","",this.tb),_ds.D(this,"hidden","",this.o));const a=await _ds.x();if(this.V=a.hasMendelFlagAccess("BookNav","enable_collapsible_book_nav")){let b;null==(b=this.parentElement)||b.insertBefore(this.tb,this.nextSibling);_ds.D(this,
"aria-label","Hide side navigation",this.tb);_ds.D(this,"data-title","Hide side navigation",this.tb);_ds.D(this,"aria-expanded","true",this.tb);let c;null==(c=this.parentElement)||c.insertBefore(this.o,this.nextSibling)}if(this.J=a.hasMendelFlagAccess("BookNav","enable_book_nav_filtering"))if(this.G=this.querySelector(".devsite-book-nav-filter"))this.g=this.G.querySelector("input[type=text]"),this.D=this.G.querySelector(".filter-clear-button"),$N(this),bO(this);NN(this);VN(this);await this.init();
XN(this)}disconnectedCallback(){this.v=!1;_ds.I(this.eventHandler);YN(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.D(this,"visually-hidden","",a);a=[this.background,this.tb,this.o];for(const b of a)b&&_ds.Zh(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.o.removeAttribute("animatable");this.o.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?
"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.D(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.tb,this.o];for(const d of c)d&&(b?_ds.D(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.K()}async init(a=!0){if(this.v){this.o.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.h=this.querySelector(".devsite-mobile-nav-bottom");_ds.D(this,"top-level-nav","");this.h&&this.h.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.D(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.D(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(cO(this),dO(this),await fO(this)):(await _ds.rj(),await eO(this))}}async ub(a){a?(a=a.querySelector("nav")||
null,cO(this,a),dO(this,a),a&&(await YN(this),this.C.clear(),XN(this,a,!1)),_ds.$g(this,this.querySelector("nav"),a)):_ds.Wh(this);if(this.J&&($N(this),this.g)){this.g.value="";let b;null==(b=this.D)||b.classList.add("hidden");bO(this)}await _ds.rj();await this.init(!1)}};hO.prototype.updateContent=hO.prototype.ub;hO.prototype.attributeChangedCallback=hO.prototype.attributeChangedCallback;hO.prototype.disconnectedCallback=hO.prototype.disconnectedCallback;hO.prototype.connectedCallback=hO.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",hO)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
